/*
 * Copyright (c) 2026 cormoran
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <zephyr/sys/iterable_sections.h>
#include <zephyr/sys/util.h>
#include <zmk/event_manager.h>

#define ZMK_CUSTOM_SETTING_SOURCE_LOCAL 0U
#define ZMK_CUSTOM_SETTING_SOURCE_ALL UINT32_MAX
#define ZMK_CUSTOM_SETTING_ARRAY_NONE UINT32_MAX

/* Supported scalar value types for custom settings. */
enum zmk_custom_setting_value_type {
    ZMK_CUSTOM_SETTING_VALUE_TYPE_BYTES = 1,
    ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32 = 2,
    ZMK_CUSTOM_SETTING_VALUE_TYPE_BOOL = 3,
    ZMK_CUSTOM_SETTING_VALUE_TYPE_STRING = 4,
    ZMK_CUSTOM_SETTING_VALUE_TYPE_BEHAVIOR = 5,
};

/* A ZMK behavior binding: a behavior local ID (see CONFIG_ZMK_BEHAVIOR_LOCAL_IDS)
 * plus its two binding parameters. Writes are validated against the target
 * behavior's parameter metadata (see zmk_behavior_validate_binding in
 * <drivers/behavior.h>) when CONFIG_ZMK_BEHAVIOR_LOCAL_IDS is enabled. */
struct zmk_custom_setting_behavior_value {
    uint32_t behavior_id;
    uint32_t param1;
    uint32_t param2;
};

/* Write mode controls whether a new value is saved, staged in RAM, or temporary. */
enum zmk_custom_setting_write_mode {
    ZMK_CUSTOM_SETTING_WRITE_MODE_MEMORY,
    ZMK_CUSTOM_SETTING_WRITE_MODE_PERSIST,
    ZMK_CUSTOM_SETTING_WRITE_MODE_TEMPORARY,
};

/* Controls whether RPC may expose the setting value. */
enum zmk_custom_setting_confidentiality {
    ZMK_CUSTOM_SETTING_CONFIDENTIALITY_DEVICE_PRIVATE,
    ZMK_CUSTOM_SETTING_CONFIDENTIALITY_RPC_PERSONAL,
    ZMK_CUSTOM_SETTING_CONFIDENTIALITY_RPC_PUBLIC,
};

/* Secure settings require Studio unlock before RPC read/write access. */
enum zmk_custom_setting_permission {
    ZMK_CUSTOM_SETTING_PERMISSION_UNSECURE,
    ZMK_CUSTOM_SETTING_PERMISSION_SECURE,
};

enum zmk_custom_setting_constraint_type {
    ZMK_CUSTOM_SETTING_CONSTRAINT_NONE,
    ZMK_CUSTOM_SETTING_CONSTRAINT_RANGE,
    ZMK_CUSTOM_SETTING_CONSTRAINT_OPTIONS,
    ZMK_CUSTOM_SETTING_CONSTRAINT_HID_USAGE,
    ZMK_CUSTOM_SETTING_CONSTRAINT_LAYER_ID,
    ZMK_CUSTOM_SETTING_CONSTRAINT_BEHAVIOR_ID,
};

enum zmk_custom_setting_changed_kind {
    ZMK_CUSTOM_SETTING_CHANGED_VALUE_UPDATED,
    ZMK_CUSTOM_SETTING_CHANGED_SAVED,
    ZMK_CUSTOM_SETTING_CHANGED_DISCARDED,
    ZMK_CUSTOM_SETTING_CHANGED_RESET,
};

struct zmk_custom_setting_value {
    enum zmk_custom_setting_value_type type;
    size_t size;
    union {
        uint8_t bytes_value[CONFIG_ZMK_CUSTOM_SETTINGS_VALUE_MAX_SIZE];
        int32_t int32_value;
        bool bool_value;
        char string_value[CONFIG_ZMK_CUSTOM_SETTINGS_VALUE_MAX_SIZE + 1];
        struct zmk_custom_setting_behavior_value behavior_value;
    };
};

struct zmk_custom_setting;

typedef int (*zmk_custom_setting_rpc_bytes_converter_t)(const struct zmk_custom_setting *setting,
                                                        const uint8_t *src, size_t src_size,
                                                        uint8_t *dest, size_t *dest_size,
                                                        size_t dest_capacity);

struct zmk_custom_setting_range {
    struct zmk_custom_setting_value min;
    struct zmk_custom_setting_value max;
};

struct zmk_custom_setting_options {
    const struct zmk_custom_setting_value *values;
    const char *const *labels;
    size_t count;
};

struct zmk_custom_setting_hid_usage {
    uint32_t usage_page;
    uint32_t usage_min;
    uint32_t usage_max;
};

struct zmk_custom_setting_constraint {
    enum zmk_custom_setting_constraint_type type;
    union {
        struct zmk_custom_setting_range range;
        struct zmk_custom_setting_options options;
        struct zmk_custom_setting_hid_usage hid_usage;
    };
};

struct zmk_custom_setting {
    const char *custom_subsystem_id;
    const char *key;
    const char *array_key;
    uint32_t array_index;
    uint32_t array_max_size;
    uint32_t default_array_size;
    uint32_t array_size;
    uint32_t persistent_array_size;
    enum zmk_custom_setting_value_type value_type;
    enum zmk_custom_setting_confidentiality confidentiality;
    enum zmk_custom_setting_permission read_permission;
    enum zmk_custom_setting_permission write_permission;
    const struct zmk_custom_setting_constraint *constraints;
    size_t constraints_count;
    /* Points at a static const object generated by the registration macros,
     * so the default lives in flash instead of being copied into this
     * (mutable, RAM-resident) struct. */
    const struct zmk_custom_setting_value *default_value;
    zmk_custom_setting_rpc_bytes_converter_t rpc_serializer;
    zmk_custom_setting_rpc_bytes_converter_t rpc_deserializer;

    bool initialized;
    bool has_persistent_value;
    /* Set on any memory-mode write, cleared on save/discard/reset. Replaces
     * comparing memory_value against a RAM-resident copy of the persisted
     * value (removed; see zmk_custom_setting_discard) so
     * zmk_custom_setting_has_unsaved_value stays a cheap flag check even
     * though it runs on the Studio RPC list hot path. */
    bool dirty;
    bool temporary_active;
    /* Index into the shared temporary-override pool (see custom_settings.c),
     * or -1 when temporary_active is false. Avoids a full-size
     * struct zmk_custom_setting_value slot per setting for a mode that is
     * rarely used and never persisted. */
    int8_t temp_slot;
    struct zmk_custom_setting_value memory_value;
};

struct zmk_custom_setting_changed {
    const struct zmk_custom_setting *setting;
    enum zmk_custom_setting_changed_kind kind;
    uint32_t source;
};

ZMK_EVENT_DECLARE(zmk_custom_setting_changed);

#define ZMK_CUSTOM_SETTING_VALUE_INT32(_value)                                                     \
    ((struct zmk_custom_setting_value){.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32,                \
                                       .int32_value = (_value)})

#define ZMK_CUSTOM_SETTING_VALUE_BOOL(_value)                                                      \
    ((struct zmk_custom_setting_value){.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_BOOL,                 \
                                       .bool_value = (_value)})

#define ZMK_CUSTOM_SETTING_VALUE_STRING(_value)                                                    \
    ((struct zmk_custom_setting_value){.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_STRING,               \
                                       .size = sizeof(_value) - 1,                                 \
                                       .string_value = (_value)})

#define ZMK_CUSTOM_SETTING_VALUE_BYTES(...)                                                        \
    ((struct zmk_custom_setting_value){                                                            \
        .type = ZMK_CUSTOM_SETTING_VALUE_TYPE_BYTES,                                               \
        .size = sizeof((uint8_t[]){__VA_ARGS__}),                                                  \
        .bytes_value = {__VA_ARGS__},                                                              \
    })

#define ZMK_CUSTOM_SETTING_VALUE_BEHAVIOR(_behavior_id, _param1, _param2)                          \
    ((struct zmk_custom_setting_value){                                                            \
        .type = ZMK_CUSTOM_SETTING_VALUE_TYPE_BEHAVIOR,                                            \
        .behavior_value = {.behavior_id = (_behavior_id),                                          \
                           .param1 = (_param1),                                                    \
                           .param2 = (_param2)},                                                   \
    })

#define ZMK_CUSTOM_SETTINGS_STRINGIFY(x) ZMK_CUSTOM_SETTINGS_STRINGIFY_INNER(x)
#define ZMK_CUSTOM_SETTINGS_STRINGIFY_INNER(x) #x

#define ZMK_CUSTOM_SETTING_NO_CONSTRAINT                                                           \
    ((struct zmk_custom_setting_constraint){.type = ZMK_CUSTOM_SETTING_CONSTRAINT_NONE})

/* Field initializers (not compound literals) so this expands to a constant
 * expression usable in a static initializer even under strict -std=c11; GCC
 * rejects an outer compound literal that nests another compound literal. */
#define ZMK_CUSTOM_SETTING_RANGE_INT32(_min, _max)                                                 \
    ((struct zmk_custom_setting_constraint){                                                       \
        .type = ZMK_CUSTOM_SETTING_CONSTRAINT_RANGE,                                               \
        .range = {.min = {.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32, .int32_value = (_min)},     \
                  .max = {.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32, .int32_value = (_max)}}})

#define ZMK_CUSTOM_SETTING_HID_USAGE(_usage_page, _usage_min, _usage_max)                          \
    ((struct zmk_custom_setting_constraint){.type = ZMK_CUSTOM_SETTING_CONSTRAINT_HID_USAGE,       \
                                            .hid_usage = {.usage_page = (_usage_page),             \
                                                          .usage_min = (_usage_min),               \
                                                          .usage_max = (_usage_max)}})

#define ZMK_CUSTOM_SETTING_LAYER_ID                                                                \
    ((struct zmk_custom_setting_constraint){.type = ZMK_CUSTOM_SETTING_CONSTRAINT_LAYER_ID})

#define ZMK_CUSTOM_SETTING_BEHAVIOR_ID                                                             \
    ((struct zmk_custom_setting_constraint){.type = ZMK_CUSTOM_SETTING_CONSTRAINT_BEHAVIOR_ID})

/* Register one custom setting in the iterable setting registry. */
#define ZMK_CUSTOM_SETTING_DEFINE(_name, _custom_subsystem_id, _key, _value_type, _default_value,  \
                                  _confidentiality, _read_permission, _write_permission,           \
                                  _constraint)                                                     \
    ZMK_CUSTOM_SETTING_DEFINE_WITH_CONSTRAINTS(_name, _custom_subsystem_id, _key, _value_type,     \
                                               _default_value, _confidentiality, _read_permission, \
                                               _write_permission, _constraint)

/* Register one custom setting with custom bytes RPC conversion hooks. */
#define ZMK_CUSTOM_SETTING_DEFINE_WITH_RPC_CONVERTERS(                                             \
    _name, _custom_subsystem_id, _key, _value_type, _default_value, _confidentiality,              \
    _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer, _constraint)          \
    ZMK_CUSTOM_SETTING_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(                                 \
        _name, _custom_subsystem_id, _key, _value_type, _default_value, _confidentiality,          \
        _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer, _constraint)

/* Register one custom setting with zero or more constraints. */
#define ZMK_CUSTOM_SETTING_DEFINE_WITH_CONSTRAINTS(_name, _custom_subsystem_id, _key, _value_type, \
                                                   _default_value, _confidentiality,               \
                                                   _read_permission, _write_permission, ...)       \
    ZMK_CUSTOM_SETTING_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(                                 \
        _name, _custom_subsystem_id, _key, _value_type, _default_value, _confidentiality,          \
        _read_permission, _write_permission, NULL, NULL, __VA_ARGS__)

#define ZMK_CUSTOM_SETTING_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(                             \
    _name, _custom_subsystem_id, _key, _value_type, _default_value, _confidentiality,              \
    _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer, ...)                  \
    BUILD_ASSERT(sizeof(_custom_subsystem_id) <=                                                   \
                     CONFIG_ZMK_CUSTOM_SETTINGS_CUSTOM_SUBSYSTEM_ID_MAX_LEN,                       \
                 "Custom subsystem id is too long");                                               \
    BUILD_ASSERT(sizeof(_key) <= CONFIG_ZMK_CUSTOM_SETTINGS_KEY_MAX_LEN,                           \
                 "Custom setting key is too long");                                                \
    static const struct zmk_custom_setting_constraint _name##_constraints[] = {__VA_ARGS__};       \
    static const struct zmk_custom_setting_value _name##_default = _default_value;                 \
    STRUCT_SECTION_ITERABLE(zmk_custom_setting, _name) = {                                         \
        .custom_subsystem_id = _custom_subsystem_id,                                               \
        .key = _key,                                                                               \
        .array_key = NULL,                                                                         \
        .array_index = ZMK_CUSTOM_SETTING_ARRAY_NONE,                                              \
        .array_max_size = 0,                                                                       \
        .default_array_size = 0,                                                                   \
        .array_size = 0,                                                                           \
        .persistent_array_size = 0,                                                                \
        .value_type = _value_type,                                                                 \
        .confidentiality = _confidentiality,                                                       \
        .read_permission = _read_permission,                                                       \
        .write_permission = _write_permission,                                                     \
        .constraints = _name##_constraints,                                                        \
        .constraints_count = ARRAY_SIZE(_name##_constraints),                                      \
        .default_value = &_name##_default,                                                         \
        .rpc_serializer = _rpc_serializer,                                                         \
        .rpc_deserializer = _rpc_deserializer,                                                     \
        .temp_slot = -1,                                                                           \
    }

/* Register one element of an array setting. _array_size is the maximum length. */
#define ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE(                                                   \
    _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,           \
    _confidentiality, _read_permission, _write_permission, _constraint)                            \
    ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_CONSTRAINTS(                                      \
        _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,       \
        _confidentiality, _read_permission, _write_permission, _constraint)

/* Register one array element with custom bytes RPC conversion hooks. */
#define ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_RPC_CONVERTERS(                               \
    _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,           \
    _confidentiality, _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer,     \
    _constraint)                                                                                   \
    ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(                   \
        _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,       \
        _confidentiality, _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer, \
        _constraint)

#define ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_CONSTRAINTS(                                  \
    _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,           \
    _confidentiality, _read_permission, _write_permission, ...)                                    \
    ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(                   \
        _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,       \
        _confidentiality, _read_permission, _write_permission, NULL, NULL, __VA_ARGS__)

#define ZMK_CUSTOM_SETTING_ARRAY_ELEMENT_DEFINE_WITH_RPC_CONVERTERS_AND_CONSTRAINTS(               \
    _name, _custom_subsystem_id, _key, _index, _array_size, _value_type, _default_value,           \
    _confidentiality, _read_permission, _write_permission, _rpc_serializer, _rpc_deserializer,     \
    ...)                                                                                           \
    BUILD_ASSERT(sizeof(_custom_subsystem_id) <=                                                   \
                     CONFIG_ZMK_CUSTOM_SETTINGS_CUSTOM_SUBSYSTEM_ID_MAX_LEN,                       \
                 "Custom subsystem id is too long");                                               \
    BUILD_ASSERT(sizeof(_key "/" ZMK_CUSTOM_SETTINGS_STRINGIFY(_index)) <=                         \
                     CONFIG_ZMK_CUSTOM_SETTINGS_KEY_MAX_LEN,                                       \
                 "Custom setting array element key is too long");                                  \
    BUILD_ASSERT((_index) < (_array_size), "Custom setting array index must be in range");         \
    static const struct zmk_custom_setting_constraint _name##_constraints[] = {__VA_ARGS__};       \
    static const struct zmk_custom_setting_value _name##_default = _default_value;                 \
    STRUCT_SECTION_ITERABLE(zmk_custom_setting, _name) = {                                         \
        .custom_subsystem_id = _custom_subsystem_id,                                               \
        .key = _key "/" ZMK_CUSTOM_SETTINGS_STRINGIFY(_index),                                     \
        .array_key = _key,                                                                         \
        .array_index = (_index),                                                                   \
        .array_max_size = (_array_size),                                                           \
        .default_array_size = (_array_size),                                                       \
        .array_size = (_array_size),                                                               \
        .persistent_array_size = (_array_size),                                                    \
        .value_type = _value_type,                                                                 \
        .confidentiality = _confidentiality,                                                       \
        .read_permission = _read_permission,                                                       \
        .write_permission = _write_permission,                                                     \
        .constraints = _name##_constraints,                                                        \
        .constraints_count = ARRAY_SIZE(_name##_constraints),                                      \
        .default_value = &_name##_default,                                                         \
        .rpc_serializer = _rpc_serializer,                                                         \
        .rpc_deserializer = _rpc_deserializer,                                                     \
        .temp_slot = -1,                                                                           \
    }

#define ZMK_CUSTOM_SETTING_FOREACH(_var) STRUCT_SECTION_FOREACH(zmk_custom_setting, _var)

const struct zmk_custom_setting *zmk_custom_setting_find(const char *custom_subsystem_id,
                                                         const char *key);
/* Find any element of an array setting by its public base key. */
const struct zmk_custom_setting *zmk_custom_setting_find_array(const char *custom_subsystem_id,
                                                               const char *key);
/* Find one element of an array setting by its public base key and element index. */
const struct zmk_custom_setting *
zmk_custom_setting_find_array_element(const char *custom_subsystem_id, const char *key,
                                      uint32_t index);
/* Return the public key exposed by RPC. Array elements return their base key. */
const char *zmk_custom_setting_public_key(const struct zmk_custom_setting *setting);
bool zmk_custom_setting_is_array(const struct zmk_custom_setting *setting);
/* Return the active array length for an array element. */
uint32_t zmk_custom_setting_array_size(const struct zmk_custom_setting *setting);
/* Return the maximum array length allocated by the registry. */
uint32_t zmk_custom_setting_array_max_size(const struct zmk_custom_setting *setting);
/* Match a setting against optional subsystem, exact key, and key-prefix filters. */
bool zmk_custom_setting_matches(const struct zmk_custom_setting *setting,
                                const char *custom_subsystem_id, const char *key,
                                const char *key_prefix);

/* Read the effective value. A temporary override takes precedence over memory value. */
int zmk_custom_setting_read(const struct zmk_custom_setting *setting,
                            struct zmk_custom_setting_value *value);
int zmk_custom_setting_read_by_key(const char *custom_subsystem_id, const char *key,
                                   struct zmk_custom_setting_value *value);
/* Read one array setting element by its public base key and element index. */
int zmk_custom_setting_read_array_by_key(const char *custom_subsystem_id, const char *key,
                                         uint32_t index, struct zmk_custom_setting_value *value);
/* Convert an internal bytes value into its RPC bytes representation. */
int zmk_custom_setting_serialize_rpc_value(const struct zmk_custom_setting *setting,
                                           const struct zmk_custom_setting_value *internal_value,
                                           struct zmk_custom_setting_value *rpc_value);
/* Convert an RPC bytes value into its internal firmware representation. */
int zmk_custom_setting_deserialize_rpc_value(const struct zmk_custom_setting *setting,
                                             const struct zmk_custom_setting_value *rpc_value,
                                             struct zmk_custom_setting_value *internal_value);

/* Write a value using the selected memory, persist, or temporary mode. */
int zmk_custom_setting_write(const struct zmk_custom_setting *setting,
                             const struct zmk_custom_setting_value *value,
                             enum zmk_custom_setting_write_mode mode);
int zmk_custom_setting_write_by_key(const char *custom_subsystem_id, const char *key,
                                    const struct zmk_custom_setting_value *value,
                                    enum zmk_custom_setting_write_mode mode);
/* Write one array setting element by its public base key and element index. */
int zmk_custom_setting_write_array_by_key(const char *custom_subsystem_id, const char *key,
                                          uint32_t index,
                                          const struct zmk_custom_setting_value *value,
                                          enum zmk_custom_setting_write_mode mode);
/* Write one array setting element and update the active array length. */
int zmk_custom_setting_write_array_element(const struct zmk_custom_setting *setting,
                                           const struct zmk_custom_setting_value *value,
                                           uint32_t array_size,
                                           enum zmk_custom_setting_write_mode mode);
/* Append one value to an array setting and grow the active length by one. */
int zmk_custom_setting_array_push_back(const struct zmk_custom_setting *setting,
                                       const struct zmk_custom_setting_value *value,
                                       enum zmk_custom_setting_write_mode mode);
/* Remove the last active array element and optionally return its previous value. */
int zmk_custom_setting_array_pop_back(const struct zmk_custom_setting *setting,
                                      struct zmk_custom_setting_value *value,
                                      enum zmk_custom_setting_write_mode mode);

/* Save the current memory value to persistent storage. */
int zmk_custom_setting_save(const struct zmk_custom_setting *setting);
/* Discard unsaved memory/temporary changes and restore the persistent/default value. */
int zmk_custom_setting_discard(const struct zmk_custom_setting *setting);
/* Erase the persistent value and restore the default value. */
int zmk_custom_setting_reset(const struct zmk_custom_setting *setting);
/* End a temporary override and reveal the current memory value again. */
int zmk_custom_setting_rollback_temporary(const struct zmk_custom_setting *setting);

/* Apply save to settings matching the optional subsystem/key/prefix filters. */
int zmk_custom_settings_save_scope(const char *custom_subsystem_id, const char *key,
                                   const char *key_prefix, uint32_t *affected_count);
/* Apply discard to settings matching the optional subsystem/key/prefix filters. */
int zmk_custom_settings_discard_scope(const char *custom_subsystem_id, const char *key,
                                      const char *key_prefix, uint32_t *affected_count);
/* Apply reset to settings matching the optional subsystem/key/prefix filters. */
int zmk_custom_settings_reset_scope(const char *custom_subsystem_id, const char *key,
                                    const char *key_prefix, uint32_t *affected_count);

bool zmk_custom_setting_has_unsaved_value(const struct zmk_custom_setting *setting);
/* Validate value type and all constraints for a setting without writing it. */
int zmk_custom_setting_validate(const struct zmk_custom_setting *setting,
                                const struct zmk_custom_setting_value *value);

/*
 * Replace a setting's default value with one resolved at boot time (e.g. from
 * devicetree data that needs behavior local IDs or other runtime-only state
 * to encode). `value` must point to storage that outlives the setting -
 * typically a caller-owned static/BSS-resident struct - since only the
 * pointer is stored, not a copy.
 *
 * Also refreshes the effective (memory) value to match, but only if no
 * persistent value has been loaded and no write has happened yet - so this
 * is safe to call from any SYS_INIT regardless of ordering relative to this
 * module's own registry init, as long as it runs before settings_load()
 * (which always happens later, from main()). Once a persisted or written
 * value exists, this only changes what a later save/discard/reset falls
 * back to.
 */
int zmk_custom_setting_set_default(const struct zmk_custom_setting *setting,
                                   const struct zmk_custom_setting_value *value);

/*
 * View-based read/write API.
 *
 * These avoid requiring callers to declare a full struct
 * zmk_custom_setting_value (sized by CONFIG_ZMK_CUSTOM_SETTINGS_VALUE_MAX_SIZE)
 * on their own stack just to read or write one small or dynamically-sized
 * value, and let bytes/string values be written from a runtime buffer
 * instead of only the compile-time-literal ZMK_CUSTOM_SETTING_VALUE_BYTES(...)
 * macro.
 */

/* Callback invoked with the effective value while the settings lock is held.
 * Runs synchronously; keep it short, copy out anything needed, and do not
 * call back into other zmk_custom_setting_* functions for the same or other
 * settings from within it. */
typedef void (*zmk_custom_setting_value_visitor_t)(const struct zmk_custom_setting_value *value,
                                                   void *user_data);

/* Borrow the effective value without copying it into a caller-owned
 * struct zmk_custom_setting_value first. */
int zmk_custom_setting_with_value(const struct zmk_custom_setting *setting,
                                  zmk_custom_setting_value_visitor_t visitor, void *user_data);

/* Copy the effective value's raw payload into a caller-sized buffer.
 * Returns -EMSGSIZE if capacity is smaller than the value. out_size and
 * out_type may be NULL. */
int zmk_custom_setting_read_into(const struct zmk_custom_setting *setting, void *buf,
                                 size_t capacity, size_t *out_size,
                                 enum zmk_custom_setting_value_type *out_type);

/* Write a BYTES or STRING setting from a runtime buffer instead of a
 * compile-time-literal value. For STRING settings, size is measured before
 * any truncation to CONFIG_ZMK_CUSTOM_SETTINGS_VALUE_MAX_SIZE. */
int zmk_custom_setting_write_bytes(const struct zmk_custom_setting *setting, const void *data,
                                   size_t size, enum zmk_custom_setting_write_mode mode);

/* Typed scalar convenience wrappers over read_into/write. Return -EINVAL if
 * the setting is not of the matching type. */
int zmk_custom_setting_get_int32(const struct zmk_custom_setting *setting, int32_t *value);
int zmk_custom_setting_set_int32(const struct zmk_custom_setting *setting, int32_t value,
                                 enum zmk_custom_setting_write_mode mode);
int zmk_custom_setting_get_bool(const struct zmk_custom_setting *setting, bool *value);
int zmk_custom_setting_set_bool(const struct zmk_custom_setting *setting, bool value,
                                enum zmk_custom_setting_write_mode mode);

/* Get/set a BEHAVIOR setting. set validates behaviorId/param1/param2 against
 * the target behavior's parameter metadata (see zmk_custom_setting_validate). */
int zmk_custom_setting_get_behavior(const struct zmk_custom_setting *setting,
                                    struct zmk_custom_setting_behavior_value *value);
int zmk_custom_setting_set_behavior(const struct zmk_custom_setting *setting,
                                    struct zmk_custom_setting_behavior_value value,
                                    enum zmk_custom_setting_write_mode mode);

/*
 * Record settings: a struct with a declared field schema, stored as a
 * versioned TLV (field id, length, value) encoding inside a BYTES setting.
 * Unknown field ids are skipped on decode and fields absent from the stored
 * data are left untouched in the destination struct (so callers should
 * populate defaults before calling zmk_custom_setting_record_get); adding a
 * field to the struct does not invalidate previously stored data.
 *
 * This builds on the existing BYTES value type and zmk_custom_setting_write_bytes/
 * read_into; there is no new RPC value type, so a record setting's RPC/export
 * representation is the encoded TLV bytes. zmk_custom_setting_record_set only
 * enforces ZMK_CUSTOM_SETTING_CONSTRAINT_NONE and
 * ZMK_CUSTOM_SETTING_CONSTRAINT_RANGE (on INT32 fields); other constraint
 * kinds fail with -ENOTSUP.
 */
#define ZMK_CUSTOM_SETTING_RECORD_VERSION 1
#define ZMK_CUSTOM_SETTING_RECORD_MAX_FIELD_SIZE 255

struct zmk_custom_setting_record_field {
    uint8_t field_id;
    size_t offset;
    size_t size;
    enum zmk_custom_setting_value_type type;
    const struct zmk_custom_setting_constraint *constraint;
};

struct zmk_custom_setting_record_schema {
    const struct zmk_custom_setting_record_field *fields;
    size_t fields_count;
    size_t record_size;
};

/* _constraint is a pointer to a separately-declared static const
 * struct zmk_custom_setting_constraint (see
 * ZMK_CUSTOM_SETTING_RECORD_RANGE_INT32_DEFINE), or NULL for no constraint.
 * It must be a pointer, not the ZMK_CUSTOM_SETTING_RANGE_INT32(...) compound
 * literal used elsewhere: nesting that inside this field's own initializer
 * hits the same non-constant-expression restriction that
 * ZMK_CUSTOM_SETTING_RANGE_INT32's own definition works around. */
#define ZMK_CUSTOM_SETTING_RECORD_FIELD_INT32(_struct, _field, _id, _constraint)                   \
    {.field_id = (_id),                                                                            \
     .offset = offsetof(_struct, _field),                                                          \
     .size = sizeof(((_struct *)0)->_field),                                                       \
     .type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32,                                                  \
     .constraint = (_constraint)}

/* Declares a named, reusable range constraint suitable for
 * ZMK_CUSTOM_SETTING_RECORD_FIELD_INT32's _constraint argument (pass
 * &_name). Uses field initializers rather than the
 * ZMK_CUSTOM_SETTING_RANGE_INT32(...) compound literal so the declaration
 * itself is a valid constant initializer. */
#define ZMK_CUSTOM_SETTING_RECORD_RANGE_INT32_DEFINE(_name, _min, _max)                            \
    static const struct zmk_custom_setting_constraint _name = {                                    \
        .type = ZMK_CUSTOM_SETTING_CONSTRAINT_RANGE,                                               \
        .range = {.min = {.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32, .int32_value = (_min)},     \
                  .max = {.type = ZMK_CUSTOM_SETTING_VALUE_TYPE_INT32, .int32_value = (_max)}}}

#define ZMK_CUSTOM_SETTING_RECORD_FIELD_BOOL(_struct, _field, _id)                                 \
    {.field_id = (_id),                                                                            \
     .offset = offsetof(_struct, _field),                                                          \
     .size = sizeof(((_struct *)0)->_field),                                                       \
     .type = ZMK_CUSTOM_SETTING_VALUE_TYPE_BOOL,                                                   \
     .constraint = NULL}

/* _field must be a fixed-size char array; the encoded/decoded length always
 * leaves room for a NUL terminator within that array. */
#define ZMK_CUSTOM_SETTING_RECORD_FIELD_STRING(_struct, _field, _id)                               \
    {.field_id = (_id),                                                                            \
     .offset = offsetof(_struct, _field),                                                          \
     .size = sizeof(((_struct *)0)->_field),                                                       \
     .type = ZMK_CUSTOM_SETTING_VALUE_TYPE_STRING,                                                 \
     .constraint = NULL}

/* Declares the fields array and schema object as two plain (non-compound-
 * literal) static objects -- required so this expands to a valid constant
 * initializer under strict -std=c11 (see ZMK_CUSTOM_SETTING_RANGE_INT32). */
#define ZMK_CUSTOM_SETTING_RECORD_SCHEMA_DEFINE(_name, _struct, ...)                               \
    static const struct zmk_custom_setting_record_field _name##_fields[] = {__VA_ARGS__};          \
    static const struct zmk_custom_setting_record_schema _name = {                                 \
        .fields = _name##_fields,                                                                  \
        .fields_count = ARRAY_SIZE(_name##_fields),                                                \
        .record_size = sizeof(_struct),                                                            \
    }

/* Encode record (a pointer to a struct matching schema) into a TLV byte
 * buffer. Returns -EMSGSIZE if it does not fit out_capacity or a field
 * exceeds ZMK_CUSTOM_SETTING_RECORD_MAX_FIELD_SIZE bytes. */
int zmk_custom_setting_record_encode(const struct zmk_custom_setting_record_schema *schema,
                                     const void *record, uint8_t *out, size_t out_capacity,
                                     size_t *out_size);

/* Decode a TLV byte buffer into record. Fields present in the data but not
 * in schema are skipped; fields in schema but absent from the data are left
 * unmodified in record. Returns -ENOTSUP for an unrecognized version byte. */
int zmk_custom_setting_record_decode(const struct zmk_custom_setting_record_schema *schema,
                                     const uint8_t *data, size_t data_size, void *record);

/* Validate record's fields against schema's constraints, then encode and
 * write it to a BYTES setting via zmk_custom_setting_write_bytes. */
int zmk_custom_setting_record_set(const struct zmk_custom_setting *setting,
                                  const struct zmk_custom_setting_record_schema *schema,
                                  const void *record, enum zmk_custom_setting_write_mode mode);

/* Read a BYTES setting's stored TLV bytes and decode them into record.
 * Populate record with defaults before calling, since fields absent from
 * the stored data are left as-is. */
int zmk_custom_setting_record_get(const struct zmk_custom_setting *setting,
                                  const struct zmk_custom_setting_record_schema *schema,
                                  void *record);
